import type { Metadata } from "next";

import "@searchlight/shared/styles/app.scss";
import "@searchlight/shared/styles/colors.scss";
import { AuthProvider } from "../lib/AuthContext";

export const metadata: Metadata = {
  title: "Searchlight 대시보드",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
